/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.registro;

import static java.lang.Integer.parseInt;
import java.awt.Color;
import com.login.login;



import java.text.SimpleDateFormat;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author Carol
 */
public class panelRegistro extends javax.swing.JFrame {
    
    JFileChooser jf = new JFileChooser();
     
    RegistrarUsuarios newRegis = new RegistrarUsuarios();
    
   
    private String foto;
    private String correo;
    private String contraseña;
    private String nombre;
    private String apellido;
    private String DpiTexto;
    private String sobreNombre;
    private String fecha;
    private String generoPersona;
    private String nacion;
    private String telefono;
    private String rolCuenta;
    private String kiosco;
    
    private int tel;
  
    
int xMouse, yMouse;
    /**
     * Creates new form panelRegistro
     */
    public panelRegistro() {
        initComponents();
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fotoPerfil = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        correoTxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        contraseñaJpass = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        regresarBtn = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        apellidoTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        dpiTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nacimiento = new com.toedter.calendar.JCalendar();
        jLabel8 = new javax.swing.JLabel();
        aliasTxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        genero = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        nacionalidad = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        telTxt = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        rol = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        kioskos = new javax.swing.JComboBox<>();
        fechaNac = new javax.swing.JTextField();
        subirBtn = new javax.swing.JButton();
        registroBtn = new javax.swing.JPanel();
        registroLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fotoPerfil.setBackground(new java.awt.Color(0, 0, 0));
        fotoPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/perfilRegistro.png"))); // NOI18N
        fotoPerfil.setBorder(null);
        fotoPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(fotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 170, 190));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Foto de perfil");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correo electronico");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 130, -1));

        correoTxt.setBackground(new java.awt.Color(0, 51, 153));
        correoTxt.setForeground(new java.awt.Color(255, 255, 255));
        correoTxt.setBorder(null);
        correoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                correoTxtMousePressed(evt);
            }
        });
        correoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoTxtActionPerformed(evt);
            }
        });
        jPanel1.add(correoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 230, 30));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setMinimumSize(new java.awt.Dimension(0, 3));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 230, 22));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        contraseñaJpass.setBackground(new java.awt.Color(0, 51, 153));
        contraseñaJpass.setForeground(new java.awt.Color(255, 255, 255));
        contraseñaJpass.setText("**********");
        contraseñaJpass.setBorder(null);
        contraseñaJpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contraseñaJpassMousePressed(evt);
            }
        });
        jPanel1.add(contraseñaJpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 230, 30));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator5.setMinimumSize(new java.awt.Dimension(0, 3));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 230, 22));

        regresarBtn.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(" Regresar");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout regresarBtnLayout = new javax.swing.GroupLayout(regresarBtn);
        regresarBtn.setLayout(regresarBtnLayout);
        regresarBtnLayout.setHorizontalGroup(
            regresarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(regresarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
        );
        regresarBtnLayout.setVerticalGroup(
            regresarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(regresarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        jPanel1.add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Registro");

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitLabel.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(0, 0, 0));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("x");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.setPreferredSize(new java.awt.Dimension(40, 40));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
            .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitBtnLayout.createSequentialGroup()
                    .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 42, Short.MAX_VALUE)))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
            .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitBtnLayout.createSequentialGroup()
                    .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 958, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");

        nombreTxt.setBackground(new java.awt.Color(255, 255, 255));
        nombreTxt.setForeground(new java.awt.Color(0, 0, 0));
        nombreTxt.setBorder(null);
        nombreTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreTxtMousePressed(evt);
            }
        });
        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });
        nombreTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreTxtKeyTyped(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setMinimumSize(new java.awt.Dimension(0, 3));

        apellidoTxt.setBackground(new java.awt.Color(255, 255, 255));
        apellidoTxt.setForeground(new java.awt.Color(0, 0, 0));
        apellidoTxt.setBorder(null);
        apellidoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                apellidoTxtMousePressed(evt);
            }
        });
        apellidoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoTxtActionPerformed(evt);
            }
        });
        apellidoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoTxtKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellido");

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setMinimumSize(new java.awt.Dimension(0, 3));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setMinimumSize(new java.awt.Dimension(0, 3));

        dpiTxt.setBackground(new java.awt.Color(255, 255, 255));
        dpiTxt.setForeground(new java.awt.Color(0, 0, 0));
        dpiTxt.setBorder(null);
        dpiTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dpiTxtMousePressed(evt);
            }
        });
        dpiTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpiTxtActionPerformed(evt);
            }
        });
        dpiTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dpiTxtKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DPI");

        jLabel7.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Fecha de nacimiento");

        nacimiento.setBackground(new java.awt.Color(255, 255, 255));
        nacimiento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        nacimiento.setDecorationBordersVisible(true);
        nacimiento.setOpaque(false);
        nacimiento.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nacimientoPropertyChange(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Sobre nombre");

        aliasTxt.setBackground(new java.awt.Color(255, 255, 255));
        aliasTxt.setForeground(new java.awt.Color(0, 0, 0));
        aliasTxt.setBorder(null);
        aliasTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aliasTxtMousePressed(evt);
            }
        });
        aliasTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aliasTxtActionPerformed(evt);
            }
        });
        aliasTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aliasTxtKeyTyped(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setMinimumSize(new java.awt.Dimension(0, 3));

        jLabel11.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Genero");

        genero.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        genero.setForeground(new java.awt.Color(0, 0, 0));
        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indefinido", "Masculino", "Femenino" }));
        genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Nacionalidad");

        nacionalidad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "otro", "Guatemalteco/a", "Mexicano/a", "Hondureño/a", "Nicaraguense", "Costarricense", "Salvadoreño/a", "Panameño/a" }));

        jLabel13.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Telefono");

        telTxt.setBackground(new java.awt.Color(255, 255, 255));
        telTxt.setForeground(new java.awt.Color(0, 0, 0));
        telTxt.setBorder(null);
        telTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telTxtActionPerformed(evt);
            }
        });
        telTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telTxtKeyTyped(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator7.setMinimumSize(new java.awt.Dimension(0, 3));

        jLabel14.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Rol");

        rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario individual", "Kiosco" }));
        rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Seleccione un kiosco");
        jLabel15.setEnabled(false);

        kioskos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        kioskos.setEnabled(false);

        fechaNac.setBackground(new java.awt.Color(255, 255, 255));
        fechaNac.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fechaNac.setForeground(new java.awt.Color(0, 0, 0));
        fechaNac.setEnabled(false);
        fechaNac.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        fechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaNacActionPerformed(evt);
            }
        });

        subirBtn.setBackground(new java.awt.Color(102, 102, 102));
        subirBtn.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        subirBtn.setForeground(new java.awt.Color(0, 0, 0));
        subirBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/iconoImg.png"))); // NOI18N
        subirBtn.setText("Subir foto");
        subirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirBtnActionPerformed(evt);
            }
        });

        registroBtn.setBackground(new java.awt.Color(153, 153, 153));
        registroBtn.setForeground(new java.awt.Color(0, 0, 0));

        registroLabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        registroLabel.setForeground(new java.awt.Color(0, 0, 0));
        registroLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registroLabel.setText("Registrarse");
        registroLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registroLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registroLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registroLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout registroBtnLayout = new javax.swing.GroupLayout(registroBtn);
        registroBtn.setLayout(registroBtnLayout);
        registroBtnLayout.setHorizontalGroup(
            registroBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        registroBtnLayout.setVerticalGroup(
            registroBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Cambiar foto de perfil (campo no obligatorio)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apellidoTxt)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(dpiTxt)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(aliasTxt)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(kioskos, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(registroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel11)
                                        .addComponent(genero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12)
                                        .addComponent(nacionalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rol, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(80, 80, 80))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subirBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dpiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(44, 44, 44)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aliasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kioskos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(subirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(registroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 750, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreTxtMousePressed

    }//GEN-LAST:event_nombreTxtMousePressed

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void apellidoTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellidoTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoTxtMousePressed

    private void apellidoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoTxtActionPerformed

    private void dpiTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dpiTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpiTxtMousePressed

    private void dpiTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpiTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpiTxtActionPerformed

    private void correoTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoTxtMousePressed

    private void correoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoTxtActionPerformed

    private void aliasTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aliasTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_aliasTxtMousePressed

    private void aliasTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aliasTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aliasTxtActionPerformed

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        exitBtn.setBackground(Color.red);
        exitLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        exitBtn.setBackground(Color.WHITE);
        exitLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitLabelMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
      login newLogin = new login();
      
      newLogin.setVisible(true);
      newLogin.setLocation(50,50);
       newLogin.setListas(newRegis);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoActionPerformed

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
        regresarBtn.setBackground(Color.DARK_GRAY);
        jLabel10.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
         regresarBtn.setBackground(Color.WHITE);
        jLabel10.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel10MouseExited

    private void telTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telTxtActionPerformed

    private void rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolActionPerformed
        if(String.valueOf(rol.getSelectedItem()).equals("Kiosco")){
            jLabel15.setEnabled(true);
            kioskos.setEnabled(true);
        }else if(String.valueOf(rol.getSelectedItem()).equals("Usuario individual")){
            jLabel15.setEnabled(false);
            kioskos.setEnabled(false);
        }
    }//GEN-LAST:event_rolActionPerformed

    private void fechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaNacActionPerformed

    private void nacimientoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nacimientoPropertyChange
      
        if(evt.getOldValue() != null){
            SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
            fechaNac.setText(ff.format(nacimiento.getCalendar().getTime()));
        }
        
    }//GEN-LAST:event_nacimientoPropertyChange

    private void subirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirBtnActionPerformed
        // TODO add your handling code here:
        
        
        
       jf.setMultiSelectionEnabled(false);
        if(jf.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            
          if( jf.getSelectedFile().getName().endsWith("jpg")||jf.getSelectedFile().getName().endsWith("png")){
               rsdragdropfiles.RSDragDropFiles.setCopiar(jf.getSelectedFile().toString(), "src/com.img/perfilRegistro.png");

            fotoPerfil.setIcon(new ImageIcon(jf.getSelectedFile().toString()));
           }else{
               mensaje("Archivo no compatible");
           }
        }
      
       
        
    }//GEN-LAST:event_subirBtnActionPerformed

    private void registroLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroLabelMouseClicked
        if (camposLlenos()) {
            if (isPassword()) {

                if (isTelefono()) {

                    if (isDpi()) {

                        registrar();
                        login newLogin = new login();
                        newLogin.setVisible(true);
                        newLogin.setLocation(50, 50);
                        newLogin.setListas(newRegis);
                        this.dispose();

                    }

                }
            }

        }


    }//GEN-LAST:event_registroLabelMouseClicked

    private void registroLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroLabelMouseEntered
        registroBtn.setBackground(Color.black);
        registroLabel.setForeground(Color.white);
    }//GEN-LAST:event_registroLabelMouseEntered

    private void registroLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroLabelMouseExited
        registroBtn.setBackground(new Color(153,153,153));
        registroLabel.setForeground(Color.black);
    }//GEN-LAST:event_registroLabelMouseExited

    private void contraseñaJpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñaJpassMousePressed
 if(String.valueOf(contraseñaJpass.getPassword()).equals("**********")){
             
             contraseñaJpass.setText("");
             contraseñaJpass.setForeground(Color.black);
        
         }    }//GEN-LAST:event_contraseñaJpassMousePressed

    private void nombreTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTxtKeyTyped
        // TODO add your handling code here:
        char C = evt.getKeyChar();
        
        if(Character.isDigit(C)){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "ingrese solo letras");
            nombreTxt.setCursor(null);
            
        }else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47 || (int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
                || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96 || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "ingrese solo letras");
            nombreTxt.setCursor(null);
            
        }
    }//GEN-LAST:event_nombreTxtKeyTyped

    private void aliasTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aliasTxtKeyTyped
        // TODO add your handling code here:
         char C = evt.getKeyChar();
        
        if(Character.isDigit(C)){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "ingrese solo letras");
            aliasTxt.setCursor(null);
            
        }else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47 || (int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
                || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96 || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "ingrese solo letras");
            aliasTxt.setCursor(null);
            
        }
    }//GEN-LAST:event_aliasTxtKeyTyped

    private void apellidoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoTxtKeyTyped
        // TODO add your handling code here:
         char C = evt.getKeyChar();
        
        if(Character.isDigit(C)){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "ingrese solo letras");
            apellidoTxt.setCursor(null);
            
        }else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47 || (int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
                || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96 || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "ingrese solo letras");
            apellidoTxt.setCursor(null);
            
        }
    }//GEN-LAST:event_apellidoTxtKeyTyped

    private void dpiTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dpiTxtKeyTyped
 char C = evt.getKeyChar();
        
        if(Character.isLetter(C)){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "ingrese solo numeros");
            dpiTxt.setCursor(null);
            
        }else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47 || (int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
                || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96 || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "ingrese solo numeros");
            dpiTxt.setCursor(null);
            
        }        
    }//GEN-LAST:event_dpiTxtKeyTyped

    private void telTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telTxtKeyTyped
         char C = evt.getKeyChar();
        
        if(Character.isLetter(C)){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "ingrese solo numeros");
            telTxt.setCursor(null);
            
        }else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47 || (int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
                || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96 || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255){
            
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "ingrese solo numeros");
            telTxt.setCursor(null);
            
        }    
    }//GEN-LAST:event_telTxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelRegistro().setVisible(true);
            }
        });
    }
    
     private void mensaje(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje);
    }
    private boolean camposLlenos() {
        String msj = "";

        this.correo = this.correoTxt.getText();
        this.contraseña = String.valueOf(this.contraseñaJpass.getPassword());
        this.nombre = this.nombreTxt.getText();
        this.apellido = this.apellidoTxt.getText();
        this.DpiTexto = this.dpiTxt.getText();
        this.sobreNombre = this.aliasTxt.getText();
        this.fecha = this.fechaNac.getText();
        this.telefono = String.valueOf(this.telTxt.getText());
        this.rolCuenta = String.valueOf(this.rol.getSelectedItem());
        this.kiosco = String.valueOf(this.kioskos.getSelectedItem());

        if (correo.isEmpty())msj += "Correo obligatorio\n";
            
        if (contraseña.equals("**********") || contraseña.isEmpty())msj += "Contraseña obligatoria\n";
        
        if (nombre.isEmpty())msj += "Nombre obligatorio\n";
        
        if (apellido.isEmpty())msj += "apellido obligatorio\n";
        
        if (DpiTexto.isEmpty())msj += "DPI obligatorio\n";
        
        if (sobreNombre.isEmpty())msj += "Alias/Sobre nombre obligatorio\n";
        
        if (fecha.isEmpty())msj += "Fecha de nacimineto obligatoria\n";
        
        if (telefono.isEmpty())msj += "Telefono obligatorio\n";
        
        if (kiosco.equals("Seleccione...") && String.valueOf(this.rol.getSelectedItem()).equals("Kiosco"))msj += "Kiosco obligatorio\n";
        
        
        if (!msj.equals("")) {
            mensaje(msj);
            return false;
        }
        return true;
    }
    
    private boolean isTelefono(){
        
       this.telefono= String.valueOf(telTxt.getText());
        if(telefono.length()==8){
            return true;
        }else{
             mensaje("Ingrese un numero de telefono valido");
        return false;}
    }
    
     private boolean isDpi(){
        this.DpiTexto=dpiTxt.getText();
        if(DpiTexto.length()==13){
            return true;
        }else{
             mensaje("Ingrese un numero de DPI valido");
        return false;}
    }
    
    
    
    private boolean isPassword(){
        this.contraseña = String.valueOf(this.contraseñaJpass.getPassword());
        
            boolean mayus = false;
            boolean num = false;
            boolean min = false;
            boolean caracter = false;
            char c;
            
            for (int i = 0; i < contraseña.length(); i++) {
            
                c = contraseña.charAt(i);
                
                if(Character.isDigit(c)){
                    num = true;
                    
                }else if(Character.isUpperCase(c)){
                     mayus = true;
                     
                }else if(Character.isLowerCase(c)){
                     min = true;
                }
                else if((int)c>32 && (int)c<=47 || (int)c>=58 && (int)c<=64
                || (int)c>=91 && (int)c<=96 || (int)c>=123 && (int)c<=255){
                     caracter = true;
                     
                    }
                     
                    }
                
            
            if(num && mayus && min && caracter ){
                return true;
            }else{
                mensaje("La contraseña debe contener:\n Mayusculas, minusculas, numeros y caracteres especiales");
            return false;
            }
          
       
    }
    
    public void setListas(RegistrarUsuarios usuarios){
        this.newRegis = usuarios;
    }
    
     private void registrar()
            
    {   
        setListas(newRegis);
        this.correo = this.correoTxt.getText();
        this.contraseña = String.valueOf(this.contraseñaJpass.getPassword());
        this.nombre = this.nombreTxt.getText();
        this.apellido = this.apellidoTxt.getText();
        this.DpiTexto = this.dpiTxt.getText();
        this.sobreNombre = this.aliasTxt.getText();
        this.fecha = this.fechaNac.getText();
        this.tel = parseInt(this.telTxt.getText());
        this.rolCuenta = String.valueOf(this.rol.getSelectedItem());
        this.kiosco = String.valueOf(this.kioskos.getSelectedItem());
        this.foto = String.valueOf(fotoPerfil.getIcon());
        this.nacion=String.valueOf(this.nacionalidad.getSelectedItem());
        this.generoPersona=String.valueOf(this.genero.getSelectedItem());
        int result=0;
        if(rolCuenta.equals("Kiosco")){
         result = this.newRegis.ReUsuarios(correo, contraseña, nombre, apellido, DpiTexto, sobreNombre, fecha, tel, rolCuenta, kiosco, nacion, generoPersona, foto);
        }else if(rolCuenta.equals("Usuario individual")){
            result = this.newRegis.ReUsuarios(correo, contraseña, nombre, apellido, DpiTexto, sobreNombre, fecha, tel, rolCuenta, "Sin kiosco", nacion, generoPersona, foto);
        }
        switch (result) {
            case 1:
                mensaje("Registrado");                
                break;
            case 2:
                mensaje("El correo: "+correo+" ya existe");
                break;
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aliasTxt;
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JPasswordField contraseñaJpass;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JTextField dpiTxt;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JTextField fechaNac;
    private javax.swing.JLabel fotoPerfil;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JComboBox<String> kioskos;
    private com.toedter.calendar.JCalendar nacimiento;
    private javax.swing.JComboBox<String> nacionalidad;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JPanel registroBtn;
    private javax.swing.JLabel registroLabel;
    private javax.swing.JPanel regresarBtn;
    private javax.swing.JComboBox<String> rol;
    private javax.swing.JButton subirBtn;
    private javax.swing.JTextField telTxt;
    // End of variables declaration//GEN-END:variables
}
