/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.user;

import com.login.Listas;
import com.login.login;

import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/**
 *
 * @author Carol
 */
public class inicioUser extends javax.swing.JFrame {

    Listas newListas;
    PerfilUserJpanel perfilP = new PerfilUserJpanel();
    RegistrarTarjetaPanel tarjetaP = new RegistrarTarjetaPanel();
    RegistroFacturacionPanel RegistroFacP = new RegistroFacturacionPanel();
    CotizacionPanel cotizarP = new CotizacionPanel();
    CompraPanel compraP = new CompraPanel();
    DescargarFacturaPanel descagarP = new DescargarFacturaPanel();
    EnviosSolicitadosPanel enviosP = new EnviosSolicitadosPanel();
    /**
     * Creates new form inicioAdmin
     */

    private String foto;
    private String correo;
    private String contraseña;
    private String nombre;
    private String apellido;
    private String DpiTexto;
    private String sobreNombre;
    private String fecha;
    private String generoPersona;
    private String nacion;
    private int telefono;
    private String rolCuenta;
    private String kiosco;

    public inicioUser() {
        initComponents();
        setDate();

        perfilBtn.setForeground(Color.WHITE);
        TarjetaCreditoBtn.setForeground(Color.WHITE);
        RegistroDatosBtn.setForeground(Color.WHITE);
       
        CotizarBtn.setForeground(Color.WHITE);
       
        VerEnviosBtn.setForeground(Color.WHITE);

    }

    public void setUsuarios(String correo, String contraseña) {
        this.correo = correo;
        this.contraseña = contraseña;
        actualizarUsuarios();
    }

    public void setListas(Listas newListas) {
        this.newListas = newListas;
        EnviosJPanel();
        DescargarJPanel();
        CompraJPanel();
        CotizarJPanel();
        RegistroFacJPanel();
        TarjetaJPanel();
        PerfilJPanel();
    }

    public void actualizarUsuarios() {
        perfilP.setListas(newListas);
        perfilP.setUsuarios(correo, contraseña);

    }
    //***************************************************

    //***************************************************
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TarjetaCreditoBtn = new javax.swing.JButton();
        RegistroDatosBtn = new javax.swing.JButton();
        CotizarBtn = new javax.swing.JButton();
        perfilBtn = new javax.swing.JButton();
        CerrarSesionBtn = new javax.swing.JButton();
        VerEnviosBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1087, 660));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(0, 51, 153));
        menu.setAutoscrolls(true);

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USAC-Delivery");

        TarjetaCreditoBtn.setBackground(new java.awt.Color(0, 0, 204));
        TarjetaCreditoBtn.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        TarjetaCreditoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/tarjeta-de-debito.png"))); // NOI18N
        TarjetaCreditoBtn.setText("Registrar Tarjeta de Credito");
        TarjetaCreditoBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        TarjetaCreditoBtn.setBorderPainted(false);
        TarjetaCreditoBtn.setContentAreaFilled(false);
        TarjetaCreditoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TarjetaCreditoBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TarjetaCreditoBtn.setIconTextGap(15);
        TarjetaCreditoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TarjetaCreditoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TarjetaCreditoBtnMouseExited(evt);
            }
        });
        TarjetaCreditoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarjetaCreditoBtnActionPerformed(evt);
            }
        });

        RegistroDatosBtn.setBackground(new java.awt.Color(0, 0, 204));
        RegistroDatosBtn.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        RegistroDatosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/informacion-personal.png"))); // NOI18N
        RegistroDatosBtn.setText("Registro de datos de Facturacion");
        RegistroDatosBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        RegistroDatosBtn.setBorderPainted(false);
        RegistroDatosBtn.setContentAreaFilled(false);
        RegistroDatosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegistroDatosBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RegistroDatosBtn.setIconTextGap(10);
        RegistroDatosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistroDatosBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistroDatosBtnMouseExited(evt);
            }
        });
        RegistroDatosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroDatosBtnActionPerformed(evt);
            }
        });

        CotizarBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        CotizarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Cotizacion.png"))); // NOI18N
        CotizarBtn.setText("Cotización de Paquetes");
        CotizarBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        CotizarBtn.setBorderPainted(false);
        CotizarBtn.setContentAreaFilled(false);
        CotizarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CotizarBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CotizarBtn.setIconTextGap(10);
        CotizarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CotizarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CotizarBtnMouseExited(evt);
            }
        });
        CotizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CotizarBtnActionPerformed(evt);
            }
        });

        perfilBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        perfilBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/perfil.png"))); // NOI18N
        perfilBtn.setText("Perfil");
        perfilBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        perfilBtn.setBorderPainted(false);
        perfilBtn.setContentAreaFilled(false);
        perfilBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perfilBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        perfilBtn.setIconTextGap(15);
        perfilBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                perfilBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                perfilBtnMouseExited(evt);
            }
        });
        perfilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilBtnActionPerformed(evt);
            }
        });

        CerrarSesionBtn.setBackground(new java.awt.Color(255, 51, 51));
        CerrarSesionBtn.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        CerrarSesionBtn.setForeground(new java.awt.Color(0, 0, 0));
        CerrarSesionBtn.setText("Cerrar sesión ");
        CerrarSesionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarSesionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarSesionBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarSesionBtnMouseExited(evt);
            }
        });
        CerrarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionBtnActionPerformed(evt);
            }
        });

        VerEnviosBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        VerEnviosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/enviado.png"))); // NOI18N
        VerEnviosBtn.setText("Envios Solicitados");
        VerEnviosBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        VerEnviosBtn.setBorderPainted(false);
        VerEnviosBtn.setContentAreaFilled(false);
        VerEnviosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerEnviosBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        VerEnviosBtn.setIconTextGap(10);
        VerEnviosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VerEnviosBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VerEnviosBtnMouseExited(evt);
            }
        });
        VerEnviosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerEnviosBtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Eliminar Cuenta");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistroDatosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CotizarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TarjetaCreditoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
            .addComponent(perfilBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(VerEnviosBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(CerrarSesionBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(perfilBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TarjetaCreditoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegistroDatosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CotizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VerEnviosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(CerrarSesionBtn)
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );

        header.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario/Cliente");

        dateText.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setText("hoy es {day} de {month} del {year}");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateText)
                    .addComponent(jLabel1))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TarjetaCreditoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarjetaCreditoBtnActionPerformed

        TarjetaJPanel();

    }//GEN-LAST:event_TarjetaCreditoBtnActionPerformed

    private void TarjetaCreditoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TarjetaCreditoBtnMouseEntered

        TarjetaCreditoBtn.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_TarjetaCreditoBtnMouseEntered

    private void RegistroDatosBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroDatosBtnMouseEntered
        // TODO add your handling code here:
        RegistroDatosBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_RegistroDatosBtnMouseEntered

    private void CotizarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CotizarBtnMouseEntered
        // TODO add your handling code here:
        CotizarBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_CotizarBtnMouseEntered

    private void TarjetaCreditoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TarjetaCreditoBtnMouseExited
        // TODO add your handling code here:
        TarjetaCreditoBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_TarjetaCreditoBtnMouseExited

    private void RegistroDatosBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroDatosBtnMouseExited
        // TODO add your handling code here:
        RegistroDatosBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_RegistroDatosBtnMouseExited

    private void CotizarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CotizarBtnMouseExited
        // TODO add your handling code here:
        CotizarBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_CotizarBtnMouseExited

    private void perfilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilBtnActionPerformed

        PerfilJPanel();


    }//GEN-LAST:event_perfilBtnActionPerformed

    private void perfilBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilBtnMouseEntered
        // TODO add your handling code here:

        perfilBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_perfilBtnMouseEntered

    private void perfilBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilBtnMouseExited
        // TODO add your handling code here:
        perfilBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_perfilBtnMouseExited

    private void CotizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CotizarBtnActionPerformed
        // TODO add your handling code here:
CotizarJPanel();

    }//GEN-LAST:event_CotizarBtnActionPerformed

    private void RegistroDatosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroDatosBtnActionPerformed
        // TODO add your handling code here:
        RegistroFacJPanel();


    }//GEN-LAST:event_RegistroDatosBtnActionPerformed

    private void CerrarSesionBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionBtnMouseEntered
        // TODO add your handling code here:
        this.CerrarSesionBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_CerrarSesionBtnMouseEntered

    private void CerrarSesionBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionBtnMouseExited
        // TODO add your handling code here:
        this.CerrarSesionBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_CerrarSesionBtnMouseExited

    private void CerrarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionBtnActionPerformed
        // TODO add your handling code here:
        login newLogin = new login();

        newLogin.setVisible(true);
        newLogin.setLocation(50, 50);
        newLogin.setListas(newListas);
        this.dispose();

    }//GEN-LAST:event_CerrarSesionBtnActionPerformed

    private void VerEnviosBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerEnviosBtnMouseEntered
        // TODO add your handling code here:
        this.VerEnviosBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_VerEnviosBtnMouseEntered

    private void VerEnviosBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerEnviosBtnMouseExited
        // TODO add your handling code here:
                this.VerEnviosBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_VerEnviosBtnMouseExited

    private void VerEnviosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerEnviosBtnActionPerformed
        // TODO add your handling code here:
        EnviosJPanel();
    }//GEN-LAST:event_VerEnviosBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        eliminar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioUser().setVisible(true);

            }
        });
    }

    private void setDate() {
        LocalDate now = LocalDate.now();
        /* 
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses={"Enero","Febrero","Marzo","Abril","Junio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"};
        dateText.setText("Hoy es "+dia+" de "+meses[month-1]+" de "+year);
         */
        Locale spanishLocale = new Locale("es", "ES");
        dateText.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'del' yyyy", spanishLocale)));
    }

    private void PerfilJPanel() {
        perfilP.setListas(newListas);
        perfilP.setUsuarios(correo, contraseña);
        perfilP.setSize(843, 440);

        perfilP.setLocation(0, 0);

        content.removeAll();
        content.add(perfilP, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    private void TarjetaJPanel() {
        tarjetaP.setListas(newListas);
        tarjetaP.setUsuarios(correo, contraseña);
        tarjetaP.setSize(843, 440);

        tarjetaP.setLocation(0, 0);

        content.removeAll();
        content.add(tarjetaP, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    private void RegistroFacJPanel() {
        RegistroFacP.setListas(newListas);
        RegistroFacP.setUsuarios(correo, contraseña);
        RegistroFacP.setSize(843, 440);

        RegistroFacP.setLocation(0, 0);

        content.removeAll();
        content.add(RegistroFacP, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
     private void CotizarJPanel() {
        cotizarP.setListas(newListas);
        cotizarP.setUsuarios(correo, contraseña);
        cotizarP.setSize(868, 684);

        cotizarP.setLocation(0, 0);

        content.removeAll();
        content.add(cotizarP, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
        private void CompraJPanel() {
        compraP.setListas(newListas);
        compraP.setUsuarios(correo, contraseña);
        compraP.setSize(843, 440);

        compraP.setLocation(0, 0);

        content.removeAll();
        content.add(compraP, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
        
      private void DescargarJPanel() {
        descagarP.setListas(newListas);
        descagarP.setUsuarios(correo, contraseña);
        descagarP.setSize(843, 440);

        descagarP.setLocation(0, 0);

        content.removeAll();
        content.add(descagarP, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
      
    private void EnviosJPanel() {
        enviosP.setListas(newListas);
        enviosP.setUsuarios(correo, contraseña);
        enviosP.setSize(900, 440);

        enviosP.setLocation(0, 0);

        content.removeAll();
        content.add(enviosP, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

private void eliminar(){
        
        
            

            this.newListas.getNewRegis().eliminar(correo, contraseña);
       login newLogin = new login();

        newLogin.setVisible(true);
        newLogin.setLocation(50, 50);
        newLogin.setListas(newListas);
        this.dispose();
        
    }
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarSesionBtn;
    private javax.swing.JButton CotizarBtn;
    private javax.swing.JButton RegistroDatosBtn;
    private javax.swing.JButton TarjetaCreditoBtn;
    private javax.swing.JButton VerEnviosBtn;
    private javax.swing.JPanel content;
    private javax.swing.JLabel dateText;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menu;
    private javax.swing.JButton perfilBtn;
    // End of variables declaration//GEN-END:variables
}
