/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.admin;

import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;


/**
 *
 * @author Carol
 */
public class inicioAdmin extends javax.swing.JFrame {

    /**
     * Creates new form inicioAdmin
     */
    public inicioAdmin() {
        initComponents();
        setDate();
        initContent();
        perfilBtn.setForeground(Color.WHITE);
        kioscoBtn.setForeground(Color.WHITE);
        preciosBtn.setForeground(Color.WHITE);
        reporteBtn.setForeground(Color.WHITE);
        departamentosBtn.setForeground(Color.WHITE);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kioscoBtn = new javax.swing.JButton();
        preciosBtn = new javax.swing.JButton();
        departamentosBtn = new javax.swing.JButton();
        reporteBtn = new javax.swing.JButton();
        perfilBtn = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1087, 660));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(0, 51, 153));
        menu.setAutoscrolls(true);

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USAC-Delivery");

        kioscoBtn.setBackground(new java.awt.Color(0, 0, 204));
        kioscoBtn.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        kioscoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/quiosco (1).png"))); // NOI18N
        kioscoBtn.setText("Manejo de Kioscos");
        kioscoBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        kioscoBtn.setBorderPainted(false);
        kioscoBtn.setContentAreaFilled(false);
        kioscoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kioscoBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kioscoBtn.setIconTextGap(15);
        kioscoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kioscoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kioscoBtnMouseExited(evt);
            }
        });
        kioscoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kioscoBtnActionPerformed(evt);
            }
        });

        preciosBtn.setBackground(new java.awt.Color(0, 0, 204));
        preciosBtn.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        preciosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/dineroICono.png"))); // NOI18N
        preciosBtn.setText("Manejo de regiones y precios");
        preciosBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        preciosBtn.setBorderPainted(false);
        preciosBtn.setContentAreaFilled(false);
        preciosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        preciosBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        preciosBtn.setIconTextGap(10);
        preciosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                preciosBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                preciosBtnMouseExited(evt);
            }
        });
        preciosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preciosBtnActionPerformed(evt);
            }
        });

        departamentosBtn.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        departamentosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Departamentos.png"))); // NOI18N
        departamentosBtn.setText("departamentos y municipios");
        departamentosBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        departamentosBtn.setBorderPainted(false);
        departamentosBtn.setContentAreaFilled(false);
        departamentosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        departamentosBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        departamentosBtn.setIconTextGap(10);
        departamentosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                departamentosBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                departamentosBtnMouseExited(evt);
            }
        });
        departamentosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentosBtnActionPerformed(evt);
            }
        });

        reporteBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        reporteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/reporte-de-negocios.png"))); // NOI18N
        reporteBtn.setText("Reporte");
        reporteBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        reporteBtn.setBorderPainted(false);
        reporteBtn.setContentAreaFilled(false);
        reporteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reporteBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reporteBtn.setIconTextGap(10);
        reporteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reporteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reporteBtnMouseExited(evt);
            }
        });
        reporteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteBtnActionPerformed(evt);
            }
        });

        perfilBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        perfilBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/perfil.png"))); // NOI18N
        perfilBtn.setText("Perfil");
        perfilBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        perfilBtn.setBorderPainted(false);
        perfilBtn.setContentAreaFilled(false);
        perfilBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perfilBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        perfilBtn.setIconTextGap(15);
        perfilBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                perfilBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                perfilBtnMouseExited(evt);
            }
        });
        perfilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(preciosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
            .addComponent(departamentosBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reporteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kioscoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(perfilBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(perfilBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(kioscoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preciosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departamentosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reporteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        header.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrador / Control");

        dateText.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setText("hoy es {day} de {month} del {year}");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateText)
                    .addComponent(jLabel1))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateText)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kioscoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kioscoBtnActionPerformed
      showJpanel(new KioscoPanel());
    }//GEN-LAST:event_kioscoBtnActionPerformed

    private void kioscoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kioscoBtnMouseEntered
 
        kioscoBtn.setForeground(Color.BLACK);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_kioscoBtnMouseEntered

    private void preciosBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preciosBtnMouseEntered
        // TODO add your handling code here:
        preciosBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_preciosBtnMouseEntered

    private void departamentosBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departamentosBtnMouseEntered
        // TODO add your handling code here:
        departamentosBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_departamentosBtnMouseEntered

    private void reporteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteBtnMouseEntered
        // TODO add your handling code here:
        reporteBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_reporteBtnMouseEntered

    private void kioscoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kioscoBtnMouseExited
        // TODO add your handling code here:
        kioscoBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_kioscoBtnMouseExited

    private void preciosBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preciosBtnMouseExited
        // TODO add your handling code here:
        preciosBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_preciosBtnMouseExited

    private void departamentosBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departamentosBtnMouseExited
        // TODO add your handling code here:
        departamentosBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_departamentosBtnMouseExited

    private void reporteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteBtnMouseExited
        // TODO add your handling code here:
        reporteBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_reporteBtnMouseExited

    private void perfilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilBtnActionPerformed
 showJpanel(new PerfilJpanel());
    }//GEN-LAST:event_perfilBtnActionPerformed

    private void perfilBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilBtnMouseEntered
        // TODO add your handling code here:
        
        perfilBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_perfilBtnMouseEntered

    private void perfilBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilBtnMouseExited
        // TODO add your handling code here:
        perfilBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_perfilBtnMouseExited

    private void departamentosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentosBtnActionPerformed
        // TODO add your handling code here:
        showJpanel(new DepartamentosPanel());
    }//GEN-LAST:event_departamentosBtnActionPerformed

    private void preciosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preciosBtnActionPerformed
        // TODO add your handling code here:
        
        showJpanel(new PreciosPanel());
        
    }//GEN-LAST:event_preciosBtnActionPerformed

    private void reporteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteBtnActionPerformed
        // TODO add your handling code here:
        showJpanel(new ReportesPanel());
    }//GEN-LAST:event_reporteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioAdmin().setVisible(true);
            }
        });
    }
    
    private void  setDate(){
      LocalDate now = LocalDate.now();
       /* 
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses={"Enero","Febrero","Marzo","Abril","Junio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"};
        dateText.setText("Hoy es "+dia+" de "+meses[month-1]+" de "+year);
*/   
      Locale spanishLocale = new Locale("es","ES");
      dateText.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'del' yyyy", spanishLocale)));
}
    private void initContent(){

        showJpanel(new PerfilJpanel());
    }
    
    private void showJpanel(JPanel p){
        p.setSize(843,440);
        p.setLocation(0,0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel dateText;
    private javax.swing.JButton departamentosBtn;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kioscoBtn;
    private javax.swing.JPanel menu;
    private javax.swing.JButton perfilBtn;
    private javax.swing.JButton preciosBtn;
    private javax.swing.JButton reporteBtn;
    // End of variables declaration//GEN-END:variables
}
