/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.admin;

import com.login.Listas;
import com.login.login;
import com.registro.RegistrarUsuarios;
import com.registro.Usuarios;
import java.awt.Color;
import java.awt.Image;
import static java.lang.Integer.parseInt;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Carol
 */
public class PerfilJpanel extends javax.swing.JPanel {
    
    Listas newListas;
    
 boolean activar = false;

    private String foto;
    private String correo;
    private String contraseña;
    private String nombre;
    private String apellido;
    private String DpiTexto;
    private String sobreNombre;
    private String fecha;
    private String generoPersona;
    private String nacion;
    private int telefono;
    private String rolCuenta;
    private String kiosco;
    /**
     * Creates new form Kioscos
     */
    public PerfilJpanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        NombreTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ApellidoTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CorreoTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ContraseñaField = new javax.swing.JPasswordField();
        EditarBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        FechaTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DPITextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TelTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        AliasTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        GeneroTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        NacionTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        RolTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        KioscoTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ActualizarBtn = new javax.swing.JButton();
        SubirBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        fotoPerfilLabel = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Bienvenido!");

        NombreTextField.setBackground(new java.awt.Color(255, 255, 255));
        NombreTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NombreTextField.setForeground(new java.awt.Color(0, 0, 0));
        NombreTextField.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Apellido");

        ApellidoTextField.setBackground(new java.awt.Color(255, 255, 255));
        ApellidoTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ApellidoTextField.setForeground(new java.awt.Color(0, 0, 0));
        ApellidoTextField.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contraseña");

        CorreoTextField.setBackground(new java.awt.Color(255, 255, 255));
        CorreoTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CorreoTextField.setForeground(new java.awt.Color(0, 0, 0));
        CorreoTextField.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Correo");

        ContraseñaField.setBackground(new java.awt.Color(255, 255, 255));
        ContraseñaField.setForeground(new java.awt.Color(0, 0, 0));
        ContraseñaField.setText("**********");
        ContraseñaField.setEnabled(false);

        EditarBtn.setBackground(new java.awt.Color(255, 255, 255));
        EditarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/editar.png"))); // NOI18N
        EditarBtn.setBorder(null);
        EditarBtn.setBorderPainted(false);
        EditarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarBtnMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Editar");

        FechaTextField.setBackground(new java.awt.Color(255, 255, 255));
        FechaTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        FechaTextField.setForeground(new java.awt.Color(0, 0, 0));
        FechaTextField.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Fecha de nacimiento");

        DPITextField.setBackground(new java.awt.Color(255, 255, 255));
        DPITextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DPITextField.setForeground(new java.awt.Color(0, 0, 0));
        DPITextField.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("DPI");

        TelTextField.setBackground(new java.awt.Color(255, 255, 255));
        TelTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TelTextField.setForeground(new java.awt.Color(0, 0, 0));
        TelTextField.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Tel.");

        AliasTextField.setBackground(new java.awt.Color(255, 255, 255));
        AliasTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        AliasTextField.setForeground(new java.awt.Color(0, 0, 0));
        AliasTextField.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Alias");

        GeneroTextField.setBackground(new java.awt.Color(255, 255, 255));
        GeneroTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        GeneroTextField.setForeground(new java.awt.Color(0, 0, 0));
        GeneroTextField.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Genero");

        NacionTextField.setBackground(new java.awt.Color(255, 255, 255));
        NacionTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NacionTextField.setForeground(new java.awt.Color(0, 0, 0));
        NacionTextField.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nacionalidad");

        RolTextField.setBackground(new java.awt.Color(255, 255, 255));
        RolTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        RolTextField.setForeground(new java.awt.Color(0, 0, 0));
        RolTextField.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Rol");

        KioscoTextField.setBackground(new java.awt.Color(255, 255, 255));
        KioscoTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        KioscoTextField.setForeground(new java.awt.Color(0, 0, 0));
        KioscoTextField.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Kiosco");

        ActualizarBtn.setBackground(new java.awt.Color(0, 0, 153));
        ActualizarBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        ActualizarBtn.setText("Actualizar");
        ActualizarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ActualizarBtn.setEnabled(false);
        ActualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBtnActionPerformed(evt);
            }
        });

        SubirBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        SubirBtn.setText("Subir foto");
        SubirBtn.setEnabled(false);
        SubirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(135, 135));

        fotoPerfilLabel.setPreferredSize(new java.awt.Dimension(135, 135));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fotoPerfilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotoPerfilLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(KioscoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(SubirBtn)
                                .addGap(40, 40, 40)
                                .addComponent(ActualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(NombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ApellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(51, 51, 51)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CorreoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ContraseñaField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AliasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GeneroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FechaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DPITextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EditarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(CorreoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ApellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(ContraseñaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(FechaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(DPITextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(TelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(AliasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(GeneroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(NacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(RolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(KioscoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubirBtn))
                        .addGap(60, 60, 60))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(ActualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBtnActionPerformed
        // TODO add your handling code here:
        if(camposLlenos()){
            actualizarUser();
            mensaje("Perfil actualizado");
            
        }
    }//GEN-LAST:event_ActualizarBtnActionPerformed

    private void EditarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarBtnMouseClicked
        // TODO add your handling code here:
     
      
      if(activar == false){
         ActualizarBtn.setEnabled(true);
         SubirBtn.setEnabled(true);
       
         ContraseñaField.setEnabled(true);
         NombreTextField.setEnabled(true);
         ApellidoTextField.setEnabled(true);
         DPITextField.setEnabled(true);
         FechaTextField.setEnabled(true);
         TelTextField.setEnabled(true);
         AliasTextField.setEnabled(true);
         GeneroTextField.setEnabled(true);
         NacionTextField.setEnabled(true);
        

        String imgX = ".\\src\\com\\img\\salir.png";
        Image img = new ImageIcon(imgX).getImage();
            img = img.getScaledInstance(32, 32   , Image.SCALE_SMOOTH);
            ImageIcon imgI = new ImageIcon(img);
            EditarBtn.setIcon(imgI);
            activar = true;
      }else if(activar){
           ActualizarBtn.setEnabled(false);
           SubirBtn.setEnabled(false);
         
         ContraseñaField.setEnabled(false);
         NombreTextField.setEnabled(false);
         ApellidoTextField.setEnabled(false);
         DPITextField.setEnabled(false);
         FechaTextField.setEnabled(false);
         TelTextField.setEnabled(false);
         AliasTextField.setEnabled(false);
         GeneroTextField.setEnabled(false);
         NacionTextField.setEnabled(false);
         

        String imgX = ".\\src\\com\\img\\editar.png";
        Image img = new ImageIcon(imgX).getImage();
            img = img.getScaledInstance(32, 32   , Image.SCALE_SMOOTH);
            ImageIcon imgI = new ImageIcon(img);
            EditarBtn.setIcon(imgI);
            activar = false;
      }
      
        
        
    }//GEN-LAST:event_EditarBtnMouseClicked

    
    private String buscarImagen(){
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("jpg, jpeg, png", "jpg", "jpeg", "png");
        fc.setFileFilter(filtro);
        
        int resp = fc.showOpenDialog(this);
        if(resp==JFileChooser.APPROVE_OPTION){
            return fc.getSelectedFile().getPath();            
        }
        return "";
    }
    private void SubirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirBtnActionPerformed
        // TODO add your handling code here:
        this.foto = buscarImagen();
        mostrarImagen(this.fotoPerfilLabel, this.foto);
    }//GEN-LAST:event_SubirBtnActionPerformed

     public void setListas(Listas newListas, String correo, String contraseña){
        this.newListas = newListas;
        this.correo = correo;
      this.contraseña = contraseña;
       System.out.println(""+contraseña+" "+correo);
       colocar();
    }
    private void colocar(){
        Usuarios usuario =  newListas.getNewRegis().buscarUsuario2(correo, contraseña);
       if(usuario!= null){
        CorreoTextField.setText(usuario.getCorreo());
        ContraseñaField.setText(usuario.getContraseña());
        NombreTextField.setText(usuario.getNombre());
        ApellidoTextField.setText(usuario.getApellido());
        foto=usuario.getFoto();
           mostrarImagen(fotoPerfilLabel, foto);
        FechaTextField.setText(usuario.getFecha());
        DPITextField.setText(usuario.getDpi());
        TelTextField.setText(String.valueOf(usuario.getTelefono()));
        AliasTextField.setText(usuario.getSobreNombre());
        GeneroTextField.setText(usuario.getGeneroPersona());
        NacionTextField.setText(usuario.getNacion());
        RolTextField.setText(usuario.getRol());
        KioscoTextField.setText(usuario.getKiosco());
        
       }
    }
     private void mostrarImagen(JLabel cuadro, String ruta){
    
        if(!ruta.equals("")){
            Image img = new ImageIcon(ruta).getImage();
            img = img.getScaledInstance(135, 135   , Image.SCALE_SMOOTH);
            ImageIcon imgI = new ImageIcon(img);
            cuadro.setIcon(imgI);
        }
    }

     private void actualizarUser(){
        if(this.correo!=null){
           
            this.contraseña=String.valueOf(this.ContraseñaField.getPassword());
            String newContraseña = String.valueOf(this.ContraseñaField.getPassword());
            String newNombre = this.NombreTextField.getText();
            String newApellido = this.ApellidoTextField.getText();
            String newDPI = this.DPITextField.getText();
            String newAlias = this.AliasTextField.getText();
            String newFechaNac = this.FechaTextField.getText();
            int newTel = parseInt(this.TelTextField.getText());
            String newRol = this.RolTextField.getText();
            String newKiosco = this.KioscoTextField.getText();
            String newNacionalidad = this.NacionTextField.getText();
            String  newGenero = this.GeneroTextField.getText();
            String newFoto = this.foto;
         
            
            this.newListas.getNewRegis().actualizar(correo,newContraseña, newNombre, newApellido, newAlias, newDPI, newFechaNac
            , newTel, newRol, newKiosco, newNacionalidad, newGenero, newFoto);
            colocar();
          
        }
    }
      private boolean camposLlenos() {
        String msj = "";

        
        String contra = String.valueOf(this.ContraseñaField.getPassword());
        String nom = this.NombreTextField.getText();
        String ape = this.ApellidoTextField.getText();
        String DpiText = this.DPITextField.getText();
        String sobreNom = this.AliasTextField.getText();
       String fech = this.FechaTextField.getText();
        String telefo = String.valueOf(this.TelTextField.getText());

 
            
        if (contra.equals("**********") || contra.isEmpty())msj += "Contraseña obligatoria\n";
        
        if (nom.isEmpty())msj += "Nombre obligatorio\n";
        
        if (ape.isEmpty())msj += "apellido obligatorio\n";
        
        if (DpiText.isEmpty())msj += "DPI obligatorio\n";
        
        if (sobreNom.isEmpty())msj += "Alias/Sobre nombre obligatorio\n";
        
        if (fech.isEmpty())msj += "Fecha de nacimineto obligatoria\n";
        
        if (telefo.isEmpty())msj += "Telefono obligatorio\n";
        
        
        
        
        if (!msj.equals("")) {
            mensaje(msj);
            return false;
        }
        return true;
    }
     private void mensaje(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje);
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarBtn;
    private javax.swing.JTextField AliasTextField;
    private javax.swing.JTextField ApellidoTextField;
    private javax.swing.JPasswordField ContraseñaField;
    private javax.swing.JTextField CorreoTextField;
    private javax.swing.JTextField DPITextField;
    private javax.swing.JButton EditarBtn;
    private javax.swing.JTextField FechaTextField;
    private javax.swing.JTextField GeneroTextField;
    private javax.swing.JTextField KioscoTextField;
    private javax.swing.JTextField NacionTextField;
    private javax.swing.JTextField NombreTextField;
    private javax.swing.JTextField RolTextField;
    private javax.swing.JButton SubirBtn;
    private javax.swing.JTextField TelTextField;
    private javax.swing.JLabel fotoPerfilLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
